version: "3.9"

services:
  localstack:
    image: localstack/localstack:2.2.0
    container_name: localstack
    ports:
      - "4566:4566"   # Main edge port for Localstack services
      - "4571:4571"   # Optional additional port
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      DATA_DIR: /tmp/localstack/data
      DEBUG: "1"
    volumes:
      - "./localstack_data:/tmp/localstack"
